responses = {
    "greetings":[
        "Hello! How can I assist you today?",
        "Hi there! What can I do for you?",
        "Greetings! How are you doing today?",
        "Hey! How can I help you today?",
        "Hi! How’s it going?",
        "Hello! What’s on your mind?",
        "Hi there! How can I support you today?",
        "Good day! How can I assist you?",
        "Hello! How can I be of service?",
        "Hey! What’s up?",
        "Hi! How can I make your day better?",
        "Hello! How are you feeling today?",
        "Greetings! What can I help you with?",
        "Hi there! How are you today?",
        "Hello! Is there anything you need?",
        "Hey! How can I help make your day better?",
        "Hi! What’s going on?",
        "Hello! How can I assist you today?",
        "Hey there! What’s on your mind?",
        "Hi! How can I help you today?"
    ],
    "sadness": [
        "I'm here for you. What happened?",
        "I’m really sorry you’re feeling this way. Do you want to talk about it?",
        "That sounds tough. How can I support you?",
        "I'm sorry you're feeling down. Is there anything I can do?",
        "I'm here to listen if you need to talk.",
        "It's okay to feel sad sometimes. What's on your mind?",
        "I understand. I'm here if you need to talk.",
        "Is there anything I can do to help you feel better?",
        "It’s okay to cry. What’s bothering you?",
        "You don't have to go through this alone.",
        "I’m really sorry you're experiencing this.",
        "Do you want to talk about what's making you sad?",
        "I'm here for you, no matter what.",
        "It sounds like you're going through a lot right now.",
        "I'm sorry you're feeling this way. How can I help?",
        "Let me know if there's anything I can do.",
        "You are not alone. I’m here for you.",
        "I wish I could take away your pain.",
        "Take your time to feel better. I'm here when you need me.",
        "It's okay to feel sad. I'm here for you."
    ],
    "anger": [
        "I'm sorry to hear that. Can I help you with something?",
        "It sounds like you're really upset. What happened?",
        "I can see why that would make you angry. Do you want to talk about it?",
        "It's okay to feel angry. What’s going on?",
        "That must have been really frustrating. How can I help?",
        "I understand you're upset. Let’s talk about it.",
        "I’m sorry you’re feeling this way. What can I do to help?",
        "It’s okay to be angry. What’s on your mind?",
        "Do you want to talk about what made you angry?",
        "I can tell you're really upset. What's wrong?",
        "I’m here to listen if you need to vent.",
        "I understand why you're angry. How can I help?",
        "That sounds frustrating. I'm here for you.",
        "It’s natural to feel angry sometimes. What's bothering you?",
        "I'm sorry you're feeling angry. Do you want to talk about it?",
        "Let’s figure out how to resolve this together.",
        "I'm here to help. What's on your mind?",
        "It's okay to feel this way. How can I support you?",
        "I'm here if you want to talk about what's making you angry.",
        "I understand. Let's talk about it."
    ],
    "love": [
        "That's great! I'm happy for you.",
        "Love is a wonderful feeling. Tell me more!",
        "That sounds amazing. How are you feeling?",
        "Love makes everything better, doesn’t it?",
        "I’m glad to hear you’re feeling this way!",
        "Love is beautiful. What’s been happening?",
        "I’m happy to hear that! Love is special.",
        "That’s wonderful news. Tell me more about it!",
        "It sounds like you’re in a really good place.",
        "Love can be so powerful. I'm happy for you.",
        "It’s great to hear you’re feeling loved.",
        "Love is such a positive emotion. How are you feeling?",
        "That’s fantastic! Love brings so much joy.",
        "I'm so glad you're feeling this way!",
        "Love is amazing. What’s been going on?",
        "I’m really happy for you. Love is great.",
        "That’s wonderful to hear! Love is everything.",
        "It’s always nice to hear about love.",
        "I’m glad to hear you’re experiencing love.",
        "Love is a wonderful thing. I’m happy for you."
    ],
    "surprise": [
        "Wow! That's interesting.",
        "That's surprising! Tell me more.",
        "Oh, really? That’s unexpected.",
        "I didn’t see that coming! What happened?",
        "That's quite a surprise. How do you feel about it?",
        "Wow, that's unexpected! What's the story?",
        "That must have been quite a shock!",
        "I’m surprised too! What happened?",
        "Oh, wow! That’s amazing.",
        "That’s really surprising news!",
        "What a surprise! How are you feeling about it?",
        "I didn’t expect that! Tell me more.",
        "That sounds surprising. What’s the story?",
        "Wow, really? That’s interesting.",
        "That’s unexpected! How do you feel?",
        "I’m surprised! What happened?",
        "Oh my, that’s quite surprising.",
        "That’s something new! Tell me about it.",
        "Wow, that’s a surprise. How do you feel?",
        "Oh wow, that’s interesting news."
    ],
    "fear": [
        "I'm sorry to hear that. Can I help you with something?",
        "That sounds scary. What happened?",
        "I understand why you’re afraid. Do you want to talk about it?",
        "It’s okay to feel scared. What’s going on?",
        "That must have been really frightening. How can I help?",
        "I’m sorry you’re feeling this way. What can I do to help?",
        "It’s natural to feel afraid sometimes. What’s on your mind?",
        "Do you want to talk about what’s making you afraid?",
        "I can tell you’re really scared. What’s wrong?",
        "I’m here to listen if you need to talk.",
        "I understand why you're scared. How can I help?",
        "That sounds really scary. I'm here for you.",
        "It’s okay to feel afraid. What’s bothering you?",
        "I'm sorry you're feeling scared. Do you want to talk about it?",
        "Let’s figure out how to handle this together.",
        "I'm here to help. What’s on your mind?",
        "It's okay to feel this way. How can I support you?",
        "I'm here if you want to talk about what's making you scared.",
        "I understand. Let's talk about it.",
        "That must have been really frightening. What happened?"
    ],
    "joy": [
        "That's great! I'm happy for you.",
        "That sounds amazing! Tell me more.",
        "I’m really glad to hear that! What happened?",
        "Joy is such a wonderful feeling. What’s making you happy?",
        "I’m so happy for you! That’s wonderful news.",
        "That’s fantastic! Tell me more about it.",
        "I'm glad to hear you're feeling joyful.",
        "That’s wonderful! How are you feeling?",
        "I’m really happy to hear that. What’s going on?",
        "Joy is contagious! What’s making you smile?",
        "I’m glad to hear you’re feeling this way!",
        "That’s great news! Tell me more.",
        "I'm so happy for you! That sounds amazing.",
        "It’s great to hear you’re feeling joyful.",
        "I’m really happy for you. What’s been happening?",
        "Joy is such a positive emotion. What’s going on?",
        "That’s fantastic! What’s making you happy?",
        "I'm glad to hear you're experiencing joy.",
        "That’s wonderful to hear! What’s the story?",
        "I’m so happy for you! That’s great news."
    ],
    "default":[
        "I'm not sure how to respond to that. Can you please clarify?",
        "I’m not familiar with that. Could you provide more details?",
        "Hmm, I don’t quite understand. Can you tell me more?",
        "I’m not sure what you mean. Could you explain further?",
        "Sorry, I didn’t catch that. Can you rephrase your question?",
        "I’m still learning and didn’t get that. Could you elaborate?",
        "I’m not sure how to help with that. Can you provide more context?",
        "I’m not certain about that. Is there anything else you’d like to discuss?",
        "I’m not sure what you’re asking. Can you give me more information?",
        "That’s a bit unclear to me. Can you explain a bit more?"
    ]
}
