yesOrNo={
    "doubtful" : [
    "Absolutely, I’m confident this will work.",
    "Yes, I'm certain that this approach is effective.",
    "Definitely, I believe this will achieve the desired outcome.",
    "Without a doubt, this is a reliable solution.",
    "Yes, I’m sure this method will provide the results you’re looking for.",
    "Absolutely, this has been proven to work in similar situations.",
    "Yes, based on what we know, this will definitely work.",
    "I’m very confident that this will meet your expectations.",
    "Certainly, this approach is well-supported and reliable.",
    "Yes, this is a tried-and-true method for solving this problem.",
    "Indeed, this approach is highly effective.",
    "Yes, I’m very sure that this will work as expected.",
    "Absolutely, this method has been successful in many cases.",
    "Definitely, I have full confidence in this approach.",
    "Yes, this solution is backed by strong evidence.",
    "Without a doubt, this will achieve the intended results.",
    "Yes, I’m convinced this will be effective.",
    "Absolutely, the data supports this approach.",
    "Yes, this method is proven to be reliable.",
    "Definitely, I’m confident in this solution.",
    "Yes, this has worked effectively in similar scenarios.",
    "Certainly, I trust this approach will work.",
    "Absolutely, this method has a high success rate.",
    "Yes, I’m certain this will yield positive results.",
    "Without question, this is a solid approach.",
    "Definitely, I believe this is the right solution.",
    "Yes, I have strong confidence in this method.",
    "Absolutely, this approach has been validated.",
    "Yes, I’m sure this will meet your needs.",
    "Definitely, this method is reliable and proven.",
    "Without a doubt, this approach will work.",
    "Yes, I’m very sure this will be successful.",
    "Absolutely, this solution has been effective for others.",
    "Yes, I’m confident this will achieve your goals.",
    "Certainly, this is a well-supported approach.",
    "Definitely, this method is effective and trustworthy.",
    "Yes, I’m confident in the effectiveness of this solution.",
    "Absolutely, the evidence supports this approach.",
    "Yes, this method is highly reliable.",
    "Without a doubt, this will deliver the results you expect.",
    "Definitely, this approach has been proven to work.",
    "Yes, I’m sure this will be a successful solution.",
    "Absolutely, this method has been successful in similar situations.",
    "Yes, I’m confident that this approach is the right choice.",
    "Definitely, this solution has a strong track record.",
    "Yes, I’m sure this will meet your expectations.",
    "Absolutely, this method is well-supported and effective.",
    "Yes, I have full confidence this will work.",
    "Without question, this approach is reliable.",
    "Definitely, this solution is tried-and-tested."
],
"general":[
    "I'm an emotional chat bot and I'm not sure about that.",
    "Sure thing , but search yourself and let me know.",
    "Haha funny, I don't want to ansewer that",
]
}