comforts={
    "sadness" : [
    "I’m here to help you through this.",
    "I'm here for you, no matter what.",
    "It's okay to not be okay.",
    "I’m here to support you.",
    "You are not alone in this.",
    "I'll be here whenever you need me.",
    "You don’t have to go through this alone.",
    "I'm here to listen.",
    "It's okay to feel this way.",
    "You can talk to me about anything.",
    "I'll stay by your side.",
    "You don’t have to face this by yourself.",
    "I'm here to comfort you.",
    "It's okay to let it out.",
    "You have my full support.",
    "I'm here to help you carry this burden.",
    "You are not alone.",
    "I’m always here for you.",
    "It's okay to lean on me.",
    "You can count on me.",
    "I’m here to offer a shoulder to cry on.",
    "You don’t have to do this alone.",
    "I'm here to give you strength.",
    "It's okay to ask for help.",
    "You are never alone.",
    "I'm here to give you comfort.",
    "It's okay to need support.",
    "You have my unwavering support.",
    "I'm here to help you through the tough times.",
    "It's okay to feel down.",
    "You can always reach out to me.",
    "I'm here to share your load.",
    "It's okay to not have all the answers.",
    "You don’t have to struggle alone.",
    "I'm here to offer my help.",
    "It's okay to feel overwhelmed.",
    "You can lean on me anytime.",
    "I'm here to support you through this.",
    "It's okay to be sad.",
    "You don’t have to hide your feelings.",
    "I'm here to provide comfort.",
    "It's okay to need someone.",
    "You can always talk to me.",
    "I'm here to help you navigate this.",
    "It's okay to feel what you’re feeling.",
    "You are not facing this alone.",
    "I'm here to stand by you.",
    "It's okay to not be okay sometimes.",
    "You can always count on my support.",
    "I'm here to offer my shoulder.",
    "It's okay to feel lost.",
    "You are not in this alone.",
    "I'm here to help you through the dark times.",
    "It's okay to seek help.",
    "You don’t have to be strong all the time.",
    "I'm here to be your support system.",
    "It's okay to feel vulnerable.",
    "You can always rely on me.",
    "I'm here to offer my assistance.",
    "It's okay to feel broken.",
    "You don’t have to go through this by yourself.",
    "I'm here to help you cope.",
    "It's okay to need a friend.",
    "You are not walking this path alone.",
    "I'm here to provide support.",
    "It's okay to let yourself feel.",
    "You can always depend on me.",
    "I'm here to offer my ear.",
    "It's okay to be upset.",
    "You don’t have to pretend to be okay.",
    "I'm here to give you a hug.",
    "It's okay to not have it all together.",
    "You are not alone in your struggles.",
    "I'm here to stand with you.",
    "It's okay to feel uncertain.",
    "You can always reach out.",
    "I'm here to be your friend.",
    "It's okay to feel pain.",
    "You don’t have to go through this alone.",
    "I'm here to help you find peace.",
    "It's okay to need time.",
    "You are not facing this by yourself.",
    "I'm here to give you comfort.",
    "It's okay to feel overwhelmed.",
    "You can always talk to me about anything.",
    "I'm here to provide a safe space.",
    "It's okay to feel exhausted.",
    "You don’t have to be alone in this.",
    "I'm here to help you through it all.",
    "It's okay to feel hurt.",
    "You are not alone in your pain.",
    "I'm here to help you heal.",
    "It's okay to need comfort.",
    "You can always rely on my support.",
    "I'm here to be a source of strength.",
    "It's okay to feel discouraged.",
    "You don’t have to face this alone.",
    "I'm here to give you hope."
],
"anger": [
    "I'm here to listen if you want to talk.",
    "It's okay to feel angry.",
    "I'm here for you, no matter what.",
    "You can vent to me.",
    "I'm here to support you.",
    "It's okay to express your feelings.",
    "You are not alone in this.",
    "I understand why you feel this way.",
    "You can talk to me about anything.",
    "I'll stay by your side.",
    "It's okay to feel frustrated.",
    "I'm here to help you work through this.",
    "You have my full support.",
    "You can let it all out.",
    "I'm here to help you carry this burden.",
    "I'm always here for you.",
    "It's okay to feel upset.",
    "You can count on me.",
    "I'm here to offer a shoulder to lean on.",
    "You don’t have to do this alone.",
    "I'm here to give you strength.",
    "It's okay to feel this way.",
    "You are never alone.",
    "I'm here to give you comfort.",
    "It's okay to need support.",
    "You have my unwavering support.",
    "I'm here to help you through the tough times.",
    "It's okay to feel annoyed.",
    "You can always reach out to me.",
    "I'm here to share your load.",
    "It's okay to not have all the answers.",
    "You don’t have to struggle alone.",
    "I'm here to offer my help.",
    "It's okay to feel this way.",
    "You can lean on me anytime.",
    "I'm here to support you through this.",
    "It's okay to be mad.",
    "You don’t have to hide your feelings.",
    "I'm here to provide comfort.",
    "It's okay to need someone.",
    "You can always talk to me.",
    "I'm here to help you navigate this.",
    "It's okay to feel what you’re feeling.",
    "You are not facing this alone.",
    "I'm here to stand by you.",
    "It's okay to feel angry sometimes.",
    "You can always count on my support.",
    "I'm here to offer my shoulder.",
    "It's okay to feel lost.",
    "You are not in this alone.",
    "I'm here to help you through the tough times.",
    "It's okay to seek help.",
    "You don’t have to be strong all the time.",
    "I'm here to be your support system.",
    "It's okay to feel vulnerable.",
    "You can always rely on me.",
    "I'm here to offer my assistance.",
    "It's okay to feel broken.",
    "You don’t have to go through this by yourself.",
    "I'm here to help you cope.",
    "It's okay to need a friend.",
    "You are not walking this path alone.",
    "I'm here to provide support.",
    "It's okay to let yourself feel.",
    "You can always depend on me.",
    "I'm here to offer my ear.",
    "It's okay to be upset.",
    "You don’t have to pretend to be okay.",
    "I'm here to give you a hug.",
    "It's okay to not have it all together.",
    "You are not alone in your struggles.",
    "I'm here to stand with you.",
    "It's okay to feel uncertain.",
    "You can always reach out.",
    "I'm here to be your friend.",
    "It's okay to feel this way.",
    "You don’t have to go through this alone.",
    "I'm here to help you find peace.",
    "It's okay to need time.",
    "You are not facing this by yourself.",
    "I'm here to give you comfort.",
    "It's okay to feel overwhelmed.",
    "You can always talk to me about anything.",
    "I'm here to provide a safe space.",
    "It's okay to feel exhausted.",
    "You don’t have to be alone in this.",
    "I'm here to help you through it all.",
    "It's okay to feel hurt.",
    "You are not alone in your pain.",
    "I'm here to help you heal.",
    "It's okay to need comfort.",
    "You can always rely on my support.",
    "I'm here to be a source of strength.",
    "It's okay to feel discouraged.",
    "You don’t have to face this alone.",
    "I'm here to give you hope."
],
"love":[
    "I love you and I'm here for you.",
    "You are cherished.",
    "You mean so much to me.",
    "I'm here to support you with love.",
    "You are loved beyond measure.",
    "My love for you is unwavering.",
    "You are not alone in this.",
    "I care for you deeply.",
    "You are my heart.",
    "I'm always here for you.",
    "You are my everything.",
    "You have my full support.",
    "You are the light of my life.",
    "I'm here to help you through anything.",
    "You are precious to me.",
    "I adore you.",
    "You are my rock.",
    "I'm here to give you strength.",
    "You are my soulmate.",
    "My heart is with you.",
    "You don’t have to do this alone.",
    "I'm here to comfort you with love.",
    "You are my world.",
    "You have my unwavering support.",
    "I'm here to help you through the tough times.",
    "You are the love of my life.",
    "You can always reach out to me.",
    "You are my forever.",
    "You don’t have to struggle alone.",
    "I'm here to offer my help.",
    "You are my everything.",
    "You can lean on me anytime.",
    "You are my heart and soul.",
    "You are loved more than you know.",
    "You don’t have to hide your feelings.",
    "I'm here to provide comfort.",
    "You are my one and only.",
    "You are my true love.",
    "You are my best friend.",
    "I'm here to help you navigate this.",
    "You are my greatest treasure.",
    "You are my better half.",
    "You are my heart's desire.",
    "You are my forever love.",
    "You can always count on my support.",
    "You are my endless love.",
    "You are my heart's delight.",
    "You are my everything.",
    "You are my one true love.",
    "You are my love.",
    "You don’t have to face this alone.",
    "You are my greatest joy.",
    "You are my soulmate.",
    "You are my heart's song.",
    "You are my one and only.",
    "You are my endless love.",
    "You are my true love.",
    "You are my heart's delight.",
    "You are my forever love.",
    "You are my everything.",
    "You are my heart and soul.",
    "You are my greatest treasure.",
    "You are my better half.",
    "You are my heart's desire.",
    "You are my forever love.",
    "You can always count on my support.",
    "You are my endless love.",
    "You are my heart's delight.",
    "You are my everything.",
    "You are my one true love.",
    "You are my love.",
    "You don’t have to face this alone.",
    "You are my greatest joy.",
    "You are my soulmate.",
    "You are my heart's song.",
    "You are my one and only.",
    "You are my endless love.",
    "You are my true love.",
    "You are my heart's delight.",
    "You are my forever love.",
    "You are my everything.",
    "You are my heart and soul.",
    "You are my greatest treasure.",
    "You are my better half.",
    "You are my heart's desire.",
    "You are my forever love.",
    "You can always count on my support.",
    "You are my endless love.",
    "You are my heart's delight.",
    "You are my everything.",
    "You are my one true love.",
    "You are my love.",
    "You don’t have to face this alone.",
    "You are my greatest joy.",
    "You are my soulmate.",
    "You are my heart's song."
],
"surprise": [
    "I'm here to help you through this surprise.",
    "You are not alone in this.",
    "It's okay to be surprised.",
    "I'm here for you, no matter what.",
    "You can talk to me about anything.",
    "I'll stay by your side.",
    "It's okay to feel this way.",
    "You don’t have to face this by yourself.",
    "I'm here to listen.",
    "It's okay to be shocked.",
    "You have my full support.",
    "I'm here to help you navigate this.",
    "You are not alone.",
    "I’m always here for you.",
    "It's okay to feel overwhelmed.",
    "You can count on me.",
    "I'm here to offer my support.",
    "You don’t have to do this alone.",
    "It's okay to need help.",
    "You are never alone.",
    "I'm here to provide comfort.",
    "It's okay to need support.",
    "You have my unwavering support.",
    "I'm here to help you through this surprise.",
    "It's okay to feel confused.",
    "You can always reach out to me.",
    "I'm here to share your load.",
    "It's okay to not have all the answers.",
    "You don’t have to struggle alone.",
    "I'm here to offer my help.",
    "It's okay to feel this way.",
    "You can lean on me anytime.",
    "I'm here to support you through this.",
    "It's okay to be startled.",
    "You don’t have to hide your feelings.",
    "I'm here to provide comfort.",
    "It's okay to need someone.",
    "You can always talk to me.",
    "I'm here to help you navigate this.",
    "It's okay to feel what you’re feeling.",
    "You are not facing this alone.",
    "I'm here to stand by you.",
    "It's okay to feel uncertain.",
    "You can always count on my support.",
    "I'm here to offer my shoulder.",
    "It's okay to feel lost.",
    "You are not in this alone.",
    "I'm here to help you through the tough times.",
    "It's okay to seek help.",
    "You don’t have to be strong all the time.",
    "I'm here to be your support system.",
    "It's okay to feel vulnerable.",
    "You can always rely on me.",
    "I'm here to offer my assistance.",
    "It's okay to feel this way.",
    "You don’t have to go through this by yourself.",
    "I'm here to help you cope.",
    "It's okay to need a friend.",
    "You are not walking this path alone.",
    "I'm here to provide support.",
    "It's okay to let yourself feel.",
    "You can always depend on me.",
    "I'm here to offer my ear.",
    "It's okay to be surprised.",
    "You don’t have to pretend to be okay.",
    "I'm here to give you a hug.",
    "It's okay to not have it all together.",
    "You are not alone in your struggles.",
    "I'm here to stand with you.",
    "It's okay to feel uncertain.",
    "You can always reach out.",
    "I'm here to be your friend.",
    "It's okay to feel this way.",
    "You don’t have to go through this alone.",
    "I'm here to help you find peace.",
    "It's okay to need time.",
    "You are not facing this by yourself.",
    "I'm here to give you comfort.",
    "It's okay to feel overwhelmed.",
    "You can always talk to me about anything.",
    "I'm here to provide a safe space.",
    "It's okay to feel exhausted.",
    "You don’t have to be alone in this.",
    "I'm here to help you through it all.",
    "It's okay to feel shocked.",
    "You are not alone in your surprise.",
    "I'm here to help you heal.",
    "It's okay to need comfort.",
    "You can always rely on my support.",
    "I'm here to be a source of strength.",
    "It's okay to feel startled.",
    "You don’t have to face this alone.",
    "I'm here to give you hope."
],
"fear": [
    "I’m here to help you through this.",
    "You are not alone in this.",
    "It's okay to feel scared.",
    "I'm here for you, no matter what.",
    "You can talk to me about anything.",
    "I'll stay by your side.",
    "It's okay to feel this way.",
    "You don’t have to face this by yourself.",
    "I'm here to listen.",
    "It's okay to be afraid.",
    "You have my full support.",
    "I'm here to help you navigate this.",
    "You are not alone.",
    "I’m always here for you.",
    "It's okay to feel fearful.",
    "You can count on me.",
    "I'm here to offer my support.",
    "You don’t have to do this alone.",
    "It's okay to need help.",
    "You are never alone.",
    "I'm here to provide comfort.",
    "It's okay to need support.",
    "You have my unwavering support.",
    "I'm here to help you through the tough times.",
    "It's okay to feel anxious.",
    "You can always reach out to me.",
    "I'm here to share your load.",
    "It's okay to not have all the answers.",
    "You don’t have to struggle alone.",
    "I'm here to offer my help.",
    "It's okay to feel this way.",
    "You can lean on me anytime.",
    "I'm here to support you through this.",
    "It's okay to feel worried.",
    "You don’t have to hide your feelings.",
    "I'm here to provide comfort.",
    "It's okay to need someone.",
    "You can always talk to me.",
    "I'm here to help you navigate this.",
    "It's okay to feel what you’re feeling.",
    "You are not facing this alone.",
    "I'm here to stand by you.",
    "It's okay to feel uncertain.",
    "You can always count on my support.",
    "I'm here to offer my shoulder.",
    "It's okay to feel lost.",
    "You are not in this alone.",
    "I'm here to help you through the tough times.",
    "It's okay to seek help.",
    "You don’t have to be strong all the time.",
    "I'm here to be your support system.",
    "It's okay to feel vulnerable.",
    "You can always rely on me.",
    "I'm here to offer my assistance.",
    "It's okay to feel this way.",
    "You don’t have to go through this by yourself.",
    "I'm here to help you cope.",
    "It's okay to need a friend.",
    "You are not walking this path alone.",
    "I'm here to provide support.",
    "It's okay to let yourself feel.",
    "You can always depend on me.",
    "I'm here to offer my ear.",
    "It's okay to feel scared.",
    "You don’t have to pretend to be okay.",
    "I'm here to give you a hug.",
    "It's okay to not have it all together.",
    "You are not alone in your struggles.",
    "I'm here to stand with you.",
    "It's okay to feel uncertain.",
    "You can always reach out.",
    "I'm here to be your friend.",
    "It's okay to feel this way.",
    "You don’t have to go through this alone.",
    "I'm here to help you find peace.",
    "It's okay to need time.",
    "You are not facing this by yourself.",
    "I'm here to give you comfort.",
    "It's okay to feel overwhelmed.",
    "You can always talk to me about anything.",
    "I'm here to provide a safe space.",
    "It's okay to feel exhausted.",
    "You don’t have to be alone in this.",
    "I'm here to help you through it all.",
    "It's okay to feel afraid.",
    "You are not alone in your fear.",
    "I'm here to help you heal.",
    "It's okay to need comfort.",
    "You can always rely on my support.",
    "I'm here to be a source of strength.",
    "It's okay to feel fearful.",
    "You don’t have to face this alone.",
    "I'm here to give you hope."
],

"joy": [
    "I'm so happy for you.",
    "You deserve all the happiness.",
    "I'm here to share your joy.",
    "You bring so much light into my life.",
    "I'm so proud of you.",
    "Your happiness is contagious.",
    "You are a ray of sunshine.",
    "You make everything brighter.",
    "I'm here to celebrate with you.",
    "Your joy is my joy.",
    "You light up the room.",
    "You have a heart of gold.",
    "You are a blessing.",
    "I'm here to support your happiness.",
    "You are a joy to be around.",
    "You deserve all the good things.",
    "You are so amazing.",
    "Your smile is infectious.",
    "I'm so glad to see you happy.",
    "You make the world a better place.",
    "You are a true friend.",
    "I'm so grateful for you.",
    "You are a source of joy.",
    "You have a beautiful spirit.",
    "You are so loved.",
    "I'm here to cheer you on.",
    "You have a heart of gold.",
    "You are a joy to my life.",
    "You are so wonderful.",
    "You make everything better.",
    "I'm so happy for your success.",
    "You are a gift.",
    "You are truly special.",
    "You are a joy to know.",
    "You are incredible.",
    "I'm so glad you're happy.",
    "You are a light in the dark.",
    "You are so precious.",
    "I'm here to share in your joy.",
    "You are a beacon of light.",
    "You are so uplifting.",
    "You have a heart of gold.",
    "You are a joy to my soul.",
    "You are so kind.",
    "You make everything worthwhile.",
    "You are a true gem.",
    "You are an inspiration.",
    "You are a joy to everyone.",
    "You are so loved.",
    "You are a source of happiness.",
    "You are truly remarkable.",
    "You bring so much joy.",
    "You are amazing.",
    "You make everything beautiful.",
    "You are a ray of sunshine.",
    "You are so wonderful.",
    "You are a true blessing.",
    "You are so special.",
    "You are a joy to be around.",
    "You are a light in my life.",
    "You are so uplifting.",
    "You make the world better.",
    "You are a joy to know.",
    "You are so inspiring.",
    "You are a true gift.",
    "You are a joy to everyone.",
    "You are truly remarkable.",
    "You bring so much light.",
    "You are a source of joy.",
    "You are so kind.",
    "You make everything worthwhile.",
    "You are a true gem.",
    "You are an inspiration.",
    "You are so loved.",
    "You are a joy to my heart.",
    "You are truly special.",
    "You bring so much joy.",
    "You are amazing.",
    "You make everything beautiful.",
    "You are a ray of sunshine.",
    "You are so wonderful.",
    "You are a true blessing.",
    "You are so special.",
    "You are a joy to be around.",
    "You are a light in my life.",
    "You are so uplifting.",
    "You make the world better.",
    "You are a joy to know.",
    "You are so inspiring.",
    "You are a true gift.",
    "You are a joy to everyone.",
    "You are truly remarkable.",
    "You bring so much light.",
    "You are a source of joy.",
    "You are so kind.",
    "You make everything worthwhile.",
    "You are a true gem.",
    "You are an inspiration.",
    "You are so loved."
]

}